version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/atlaseolica-back-end
    
    steps:
      - when: # only execute when triggered by the api
          condition:
            not:     
              equal: [<< pipeline.trigger_source >>, api]
          steps:
            - run:
                name: Exit Pipeline
                command: exit 0
      - checkout
      # Instalação de dependências
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest flake8 bandit
      # Execução dos testes
      - run:
          name: Run Tests
          command: |
            pytest .
      
      # Execução de lint
      - run:
          name: Run Lint
          command: |
            flake8 .
      
      # Execução do Bandit para análise de segurança
      - run:
          name: Run Bandit
          command: |
            bandit -r . || (echo "Bandit found issues!"" && false)

  
workflows:
  my_workflows:
    jobs:
      - build