version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      - image: postgres:latest
        environment:
          #POSTGRES_DB: your_database_name
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
    
          
    working_directory: ~/atlaseolica-back-end
    
    steps:
      - checkout
      # Instalação de dependências
      - run:
          name: Install Dependencies
          command: |
            conda install mamba -n base -c conda-forge
            mamba create -n atlas python=3.11.8 -c conda-forge --yes
            echo "source activate atlas" > ~/.bashrc
            mamba install pip gdal rasterio -n atlas -c conda-forge --yes
            echo 'export PATH="/opt/conda/envs/atlas/bin:$PATH"' >> $BASH_ENV
            pip install psycopg2-binary
            pip install -r requirements.txt
            pip install pytest flake8 bandit
      # Execução dos testes
      - run:
          name: Run Tests
          command: |
            pytest test
      
      # Execução de lint
      - run:
          name: Run Lint
          command: |
            flake8 .
      
      # Execução do Bandit para análise de segurança
      - run:
          name: Run Bandit
          command: |
            bandit -r . --exclude repositories/geo_repository.py  || (echo "Bandit found issues!" && false)

  
workflows:
  my_workflows:
    jobs:
      - build