version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
      - image: postgres:latest
        environment:
          #POSTGRES_DB: your_database_name
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
    
          
    working_directory: ~/atlaseolica-back-end
    
    steps:
      - checkout
      # Instalação de dependências
      - run:
          name: Install Dependencies
          command: |
            sudo apt install build-essential libgdal-dev gdal-bin -y
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest flake8 bandit GDAL
      # Execução dos testes
      - run:
          name: Run Tests
          command: |
            pytest test
      
      # Execução de lint
      - run:
          name: Run Lint
          command: |
            flake8 .
      
      # Execução do Bandit para análise de segurança
      - run:
          name: Run Bandit
          command: |
            bandit -r . --exclude repositories/geo_repository.py  || (echo "Bandit found issues!" && false)

  
workflows:
  my_workflows:
    jobs:
      - build